name: Publicar Destaque no Facebook

on:
  schedule:
    - cron: '0 15 * * *' 
  workflow_dispatch: 

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar Bibliotecas
        run: pip install requests Pillow

      - name: Executar Bot do Facebook
        env:
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        run: python bot_facebook.py
